### ISSUE TITLE
Crafting and mod incompatibilities

### ISSUE THREAD

**Issue by SamuelUlep** [SolipIngen/minecraft.progressivearchery#46]
First of all thank you for the mod, Minecraft's long range combat is a bit lack luster. I have some problems with the mod though:

1. Trying to craft potion tipped kid arrows with REI, just shows a generic crafting recipe instead for the specific potion effect.
2. The quiver is kind of janky, it works with crossbows, but doesn't seem to want to work with the normal vanilla bow, I haven't tried it with the other bows yet though, not sure if it breaks with them too or not.
3. Will you be adding EMI integration in the future?
4. I tried using the quiver with the trinkets mod but it seems like I can't add the quiver to the backpack slot which I assume the quiver would've been in.
5. In the fletching table seeing as it's called the fletching table, I would've assumed I won't need a lava bucket to craft the item or a stonecutter to make arrows as I would assume the fletching table would have all the tools necessary for making arrows. If your not going to remove that aspect of the mod, then perhaps a template can replace it? An `Arrow tip` and/or `Potion tipped` template instead of a lava bucket and a stone cutter?

**Comment by SolipIngen** [comment]
Thank you for writing in, I'm grateful you like the mod and its idea.

1. Tipped (and Kid) Arrows can be obtained either with the vanilla recipe, or by a new non-crafting method added by the mod. An Advancement (visible after obtaining Flint or Copper Arrows) hints at how to get them. If you still find the method too obscure, please do let me know.
2. The Quiver, as far as I am aware, is not designed to work with the vanilla Bow and Crossbow. This is intentional, but if you think the Quiver should work with those as well, please feel free to let me know. (Replacing the vanilla items with the modded Wodden variants can be done, but I've decided against it in order to prevent unwanted corruptions of existing Bows for players.)
3. As further versions of the mod come along, I may expand integration with other mods, so please be patient, and thank you for mentioning EMI.
4. Likewise for Trinkets, as the backpack slot is probably a Trinkets unique feature that needs integration.
5. The idea was, in order to craft arrows with metals, one would need to forge them using a hot heat source, and to create kid arrows, to saw them in half. Neither the lava bucket/stonecutter should be consumed. Adding another template when the Bow Fusion Template is already added seems a bit excessive, though I can also see why the lava bucket/stonecutter recipes can be counterintuitive. Perhaps another Advancement to guide players or an alternative Fletching ingredient would do? I'll think about this.

**Comment by SamuelUlep** [comment]
1. My complaints for the tipped arrow is not because of its vagueness, just wanted to point out that it shows a generic recipe instead of a dedicated one to each special effect. Just in case you missed it while coding in the recipe.
2. IMO don't change the vanilla bow, I'm not that knowledgeable about modding but shouldn't it be possible to make the game think the quiver is just an extra inventory slot that stores more arrows like an inventory chest for bows.
Also the quiver at first was kind of confusing to use, thought I had to right click it to opens its inventory, or maybe it had some keybind or maybe some craftable recipe to add arrows into it. Turns out I just had to drag and drop arrows with right click to place it inside the quivers inventory.
3. Thanks for that, I love EMI's recipe tree that REI and JEI doesn't have.
4. Thanks for the update for this too, it just feels weird to be able to use the quiver but yet have the chest exposed when archers can and do wear armor in the Medieval era.
5. How about having the crafting of the metal bits (or materials stronger than metal i.e. diamonds and gold) be done in the smithing table and the final combination of the arrowhead, shaft and fletching be done in the fletching table?

**Comment by SolipIngen** [comment]
Some of your suggested fixes/changes have been implemented in the latest v1.1.3 versions.
 - REI tipped kid arrow recipes are now fixed and should show up properly by potions.
 - A split version ("[...]+trinkets") is now compatible with Trinkets, adding the Quiver to the Back slot.
 - The Wooden (Cross)Bows have now replaced and been merged with their vanilla versions, getting rid of the redundant Wooden weapons.

The mod's Wooden arrow is the most basic arrow and aims to replace the vanilla arrow. It's a bit weaker, but much cheaper for the early game. The Flint arrow is actually a bit stronger than the vanilla arrow, at the cost of some extra string in the Fletching recipe.

Other mods, such as EMI, may receive integration in the future, though I cannot guarantee when.
Thank you for your comments, they have been very helpful in updating the mod. I will close this Issue thread, but please feel free to open a new thread should new bugs/issues arise.
