### ISSUE TITLE
Cannot craft every arrow

### ISSUE THREAD

**Issue by SamayaNL** [SolipIngen/minecraft.progressivearchery#70]
I'm not sure if I'm doing something wrong. I read the description of the mod, but I do not see any explanation I'm looking for.

I can craft flint arrows in the fletching table, but I'm unsure how to craft other types of arrows, because when I insert golden or iron arrow heads, it doesn't craft the corresponding arrow. 

It would also be really helpful of every bow and arrow type had a tooltip describing its abilities. 

Take care!

**Comment by SamayaNL** [comment]
Oh forgot to mention, when I click on an arrow type, it does not give me a crafting recipe. It only shows what mobs drop the arrow, or where it can be looted.

**Comment by SolipIngen** [comment]
Thank you for writing in.

If you have an ingot or a diamond, you may have seen a new recipe for certain arrowhead items. Craft those arrowheads, then place them at the head slot of the fletching table. The body is the corresponding ingot (diamond arrows take iron ingots), and the tail is a fletch, e.g. feather or striderhair. In the addition slot, add a "welding" ingredient, such as a lava bucket.

FYI, this mod has integration with the recipe-accessing mods EMI (recommended) and REI. All fletching and tipping recipes are displayed when you have those mods as well.

Vanilla-wise, I had kept details/hints minimal in the sprit of how certain vanilla features are not explained explicitly in-game. However, thank you for the tooltip suggestion, I may implement that in the next update, planned for at least when MC 1.21.1 is released.

If you have further questions, please let me know here. Otherwise, if no updates are made in the couple days, I will close this Issue.

**Comment by SamayaNL** [comment]
Hey thanks for your answer!

Yeah I see where my problem was, I used sticks as the body. I did have JEI
installed, not sure if it should work with that one also, but it didn't
display any recipes for me.

You can close it.

Thanks

**Comment by SolipIngen** [comment]
Good to hear.

JustEnoughItems (JEI) is currently not integrated, it is EMI and RoughlyEnoughITems(REI) that are integrated. Therefore, JEI should not display the recipes from this mod, unless there's some cross-compatibility mod that allows REI integrated mods to be read in JEI and vice versa.

I may actually take your tooltip suggestion for the next update, as well as give the mod pages on Modrinth/CurseForge a needed update. Thanks for writing in.
