### ISSUE TITLE
Incompatibility with Sinytra Connector (1.20.1)

### ISSUE THREAD

**Issue by RaptorZeraora** [SolipIngen/minecraft.progressivearchery#72]
I tried using this mod with Sinytra Connector, but found it to be incompatible, every version without trinkets I tested was proven to be incompatible

In case you dont know what Sinytra Connector is, its basically a mod that allows fabric mods to be played on forge, so you dont need to port it to forge

https://www.curseforge.com/minecraft/mc-mods/sinytra-connector

**Comment by SolipIngen** [comment]
Thank you for writing in.

Integration with Sinytra is actually on my list of suggestions that I'm seriously considering.
Unfortunately, due to sheer real-life constraints, updating for older versions of MC is not supported. Since Sinytra is currently on MC 1.20.1, this mod will not be integrating with Sinytra as of the moment.

However, if and when Sinytra catches up to the latest version, then integration may be included in an update. Please feel free to stay tuned.

**Comment by RaptorZeraora** [comment]
Except the problem is for the 1.20.1 version of the progressive archery mod
