### ISSUE TITLE
Tipping arrows can crash you because Cauldron Behavior is "null"

### ISSUE THREAD

**Issue by OliverDK75** [SolipIngen/minecraft.progressivearchery#76]
![image](https://github.com/user-attachments/assets/37b5aeec-ca3e-4501-8c62-ed26763538b4)

I've tried it with normal arrows and tipped arrows

Mod Version is : progressivearchery-1.1.4-1.20.2+trinkets

**Comment by SolipIngen** [comment]
Hello, thank you for reporting this issue.

Unfortunately, your played version seems to be an older one. As of the moment, back-updates for older versions are not supported, mostly due to real-life constraints on this single-person passion project.

Please consider playing on the most recent versions, as each newer version aims to fix known/reported issues. I believe the newest version is stable in terms of cauldron behaviour. Of course, if there are any issues there, please feel free to report them in a new Issue thread.
